<?php

namespace Hadonra\Bundle\TransactionBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends DocumentRepository
{
}
