<?php

namespace Hadonra\Bundle\TransactionBundle\Repository\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends DocumentRepository
{
}
